### PR TITLE
Cqr

### PR DESCRIPTION
**Pull request by MojiFarmanbar**
**This is a draft pull request**
- Implementing CQR based on [Romano's paper](https://arxiv.org/pdf/1905.03222.pdf)
- added cqr_test in my folder then you can test it
- limitations:
  - at moment, it is only limited to QuantileRegressor approach from MLJInterface
  - It can be extended to MLJScikitLearnInteface (unfortunately I got into some issue that couldn't resolve it). If I get it working I would extend API to support it.
  - As QuantileRegressor is a linear model, the performance of the model is poor when it comes to non-linear cases.

> PR might fail, as I didn't merge main into this branch. After removing .vscode setting from main, I can fix it.

### CODE REVIEW

**Comment by pat-alt** [comment]
I think this branch was out-of-date? Have now merged updates from main

**Comment by pat-alt** [comment]
Notes from chat:

- [ ] Instead of if statement, use type condition for constructor: currently set to `Model<:Supervised`, use more restrictive instead (e.g. `MLJLinearModels.QuantileRegressor`).
- [ ] Union type:

```julia
"Union type for quantile models."
const QuantileModel = Union{MLJModels.QuantileRegressor, MLJ.QuantileClassifier, ScikitLearn.QuantileTrees}

"Constructor for `ConformalQuantileRegressor`."
mutable struct ConformalQuantileRegressor{Model<:QuantileModel} <: ConformalInterval
```

**Comment by MojiFarmanbar** [comment]
@pat-alt , I have adjusted based on above checklist, please review and check the PR. at the moment, it is only for one model (QuantileRegression). I will extend it to more models in another PR.

**Comment by pat-alt** [comment]
Hey @MojiFarmanbar, I'm a bit confused that when I'm trying to add a review it shows so many files changed. Have just removed the merge conflicts so that we can see if tests pass. Once they pass, I'm happy to merge this based on what we discussed and contingent on the check list items being done (as you mentioned).

**Comment by pat-alt** [comment]
Hi @MojiFarmanbar, only missing thing here is the error in docs. Other errors are unrelated to this PR, will have a crack at that next week hopefully

**Pull request merged**
