### PR TITLE
Jackknife plus ab

### PR DESCRIPTION
**Pull request by MojiFarmanbar**
Implementing the following methods:
- Jackknife plus after bootstrapping
- Jackknife plus minmax
- ~~Ensemble batch prediction interval~~

In order to run it, Ditributions and StatsBase packages must be added to ConformalPrediction package.

### CODE REVIEW

**Review by pat-alt — CHANGES_REQUESTED** [review]
Hey man, 

this looks great, thanks a lot! We'll discuss in detail on Wednesday, but for now just one question: do we need `Distributions`? At first sight, I can't see where you're actually using it here. 

If we do need it, can you explicitly specify what you use like I did now for `StatsBase`? That avoids namespace conflicts with `MLJBase`. 

Cheers!

**Comment by MojiFarmanbar** [comment]
hey Pat,

you are right, it is not needed. I removed it.

**Review by pat-alt — APPROVED** [review]

**Review by pat-alt — COMMENTED** [review]
A few more minor things, probably best discussed on tomorrow:

- `nsampling` currently defaults to `2`: is that a sensible default?
- `replacement` default to `false`: isn't bootstrap normally done with resampling? https://en.wikipedia.org/wiki/Bootstrapping_(statistics)
- Do we need `replacement` as an optional argument?
- and just a bullet point for me to remember to understand the try-catch

I'm about a to also push a few more minor changes that just slightly refactor the way that aggregation is handled.

**Comment by pat-alt** [comment]
More comments from our meeting:

- [ ] Remove the `replace` argument
- [ ] Add an argument for bootstrap size $B$, default $n/2$
- [ ] Revisit EnbPI (and comment out for now)

**Comment by MojiFarmanbar** [comment]
hey Pat,

I have adjusted the code as we discussed. it seems in [MAPIE](https://mapie.readthedocs.io/en/latest/generated/mapie.subsample.Subsample.html?highlight=subsample#mapie.subsample.Subsample), they use the default value of 30 for nsampling.

please check all is ok

**Comment by pat-alt** [comment]
Ok, awesome, I think this all looks good! Will merge in a few moments and then push a new release to General.

So to summarise, this PR contributes:

- Jackknife plus after bootstrapping
- Jackknife plus minmax after bootstrapping

As discussed, we'll revisit EnbPI in #57 

Thanks again!

**Pull request merged**
